import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { RouteProvider } from "@/providers/router-provider";
import { ConvexClientProvider } from "@/providers/convex-provider";
import { Theme } from "@/providers/theme";
import { AppearanceProvider } from "@/providers/appearance-provider";
import { Toaster } from "@repo/ui/untitledui/application/notifications/toaster";
import "@repo/ui/globals.css";
import { cx } from "@repo/ui/utils";

const inter = Inter({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-inter",
});

export const metadata: Metadata = {
    title: "Chatbot — Untitled UI",
    description: "Generated by Untitled UI CLI",
};

export const viewport: Viewport = {
    themeColor: "#7f56d9",
    colorScheme: "light dark",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={cx(inter.variable, "bg-primary antialiased")}>
                <ClerkProvider>
                    <ConvexClientProvider>
                        <RouteProvider>
                            <Theme>
                                <AppearanceProvider>
                                    {children}
                                    <Toaster />
                                </AppearanceProvider>
                            </Theme>
                        </RouteProvider>
                    </ConvexClientProvider>
                </ClerkProvider>
            </body>
        </html>
    );
}
